config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users,  :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth" }
  resources :users, only: [:show]
  root 'stories#index'

  get '/about' => 'welcome#index'

  post '/addrecommendation' => 'books#addRecommendation'
  match '/deleterecommendation' => 'books#deleteRecommendation', :via => :delete, :as => :delete_recommendation

  resources :stories, except: [:index] do
    member do
      post :like
    end
  end

  as :users do
    match '/users' => 'users#index', :via => :get, :as => :show_all_users
    match '/dashboard' => 'users#dashboard', :via => :get, :as => :user_dashboard
    match '/deleteaccount' => 'users#destroy', :via => :get, :as => :delete_my_account
    match '/inviteuser' => 'users#create_invitation', :via => :post, :as => :invite_user
  end

  as :books do
    match '/currentlyreadinglist' => 'books#addToCurrentlyReading', :via => :post, :as => :add_to_currently_reading
    match '/wishlist' => 'books#addToWishList', :via => :post, :as => :add_to_wish_list
    match '/read' => 'books#addToAlreadyRead', :via => :post, :as => :add_to_read
    match '/destroycurrentlyreading/:id' => 'books#destroyCurrentlyReading', :via => :delete, :as => :remove_from_currently_reading
    match '/destroywishlist/:id' => 'books#destroyWishList', :via => :delete, :as => :remove_from_wish_list
    match '/destroyalreadyread/:id' => 'books#destroyAlreadyRead', :via => :delete, :as => :remove_from_already_read
  end

end

app/views/shared/_activities.html.erb
<ul class="list-group custom-well">
  <% @activities.each do |activity| %>
    <li class="list-group-item user-activity">
      <small class="text-muted datetime-text"><%= time_ago_in_words(activity.created_at) %> ago @ <%= activity.created_at.strftime('%l:%M %p %A, %d %b %Y') %></small>
      <div class="activity-description">
        <% if activity.owner %>
          <% if current_user == activity.owner %>
            <strong><%= link_to "You", user_path(User.where(email: activity.owner.email)[0].id) %></strong>
          <% else %>
            <strong class="owner-name"><%= link_to activity.owner.name, user_path(User.where(email: activity.owner.email)[0].id) %></strong>
          <% end %>
        <% end %>
        <% if activity.trackable %>
          <% if activity.trackable_type == "Like" %>
            <%= render_activity(activity, display: :i18n) %>
            "<%= link_to Story.find(activity.trackable.story_id).title, story_path(activity.trackable.story_id) %>"
          <% elsif  activity.trackable_type == "BooksWishlist" %>
            added
            "<%= link_to activity.trackable.title, books_path(:title => activity.trackable.title) %>"
            <%= render_activity(activity, display: :i18n) %>
          <% elsif  activity.trackable_type == "Story" %>
            <%= render_activity(activity, display: :i18n) %>
            "<%= link_to activity.trackable.title, story_path(activity.trackable) %>"
          <% elsif  activity.trackable_type == "Recommendation" %>
            <%= render_activity(activity, display: :i18n) %>
            <% book_title = Book.find(activity.title).title %>
            "<%= link_to book_title, books_path(:title => book_title) %>"

          <% elsif  activity.trackable_type == "Book" and activity.key == "book.update"%>
            <%= render_activity(activity, display: :i18n) %>
            "<%= link_to activity.trackable.title, books_path(:title => activity.trackable.title) %>"
          <% else %>
            added
            "<%= link_to activity.trackable.title, books_path(:title => activity.trackable.title) %>"
            <%= render_activity(activity, display: :i18n) %>
          <% end %>
        <% elsif activity.title %>
          <% if activity.trackable_type == "Like" %>
            <%= render_activity(activity, display: :i18n) %>
            "<%= activity.title %>"
          <% elsif  activity.trackable_type == "BooksWishlist" %>
            added
            "<%= activity.title %>"
            <%= render_activity(activity, display: :i18n) %>
          <% elsif  activity.trackable_type == "Story" %>
            <%= render_activity(activity, display: :i18n) %>
            "<%= activity.title %>"
          <% else %>
            added
            "<%= activity.title %>"
            <%= render_activity(activity, display: :i18n) %>
          <% end %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_inviteForm.html.erb
<%= form_tag invite_user_path, method: :post, id: 'invite-user-form', class: 'custom-well' do %>
  <h4 class="dashboard__formheading">Invite your fellow <span class="shopify-green-text">Shopifolks</span></h4>
  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag :email, nil, :required => true, placeholder: "bookgeek@shopify.com", class: "form-control" %>
  </div>
  <%= submit_tag("Send Invite", :class => 'btn btn-success') %>
<% end %>