config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users,  :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth" }
  resources :users, only: [:show]
  root 'stories#index'

  get '/about' => 'welcome#index'

  post '/addrecommendation' => 'books#addRecommendation'
  match '/deleterecommendation' => 'books#deleteRecommendation', :via => :delete, :as => :delete_recommendation

  resources :stories, except: [:index] do
    member do
      post :like
    end
  end

  as :users do
    match '/users' => 'users#index', :via => :get, :as => :show_all_users
    match '/dashboard' => 'users#dashboard', :via => :get, :as => :user_dashboard
    match '/deleteaccount' => 'users#destroy', :via => :get, :as => :delete_my_account
    match '/inviteuser' => 'users#create_invitation', :via => :post, :as => :invite_user
  end

  as :books do
    match '/currentlyreadinglist' => 'books#addToCurrentlyReading', :via => :post, :as => :add_to_currently_reading
    match '/wishlist' => 'books#addToWishList', :via => :post, :as => :add_to_wish_list
    match '/read' => 'books#addToAlreadyRead', :via => :post, :as => :add_to_read
    match '/destroycurrentlyreading/:id' => 'books#destroyCurrentlyReading', :via => :delete, :as => :remove_from_currently_reading
    match '/destroywishlist/:id' => 'books#destroyWishList', :via => :delete, :as => :remove_from_wish_list
    match '/destroyalreadyread/:id' => 'books#destroyAlreadyRead', :via => :delete, :as => :remove_from_already_read
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  before_destroy :pause_tracking
  after_destroy :resume_activities
  has_many :recommendation, dependent: :destroy

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user },
          title: Proc.new { |controller, model| model.title }

  def pause_tracking
    Book.public_activity_off
    return true
  end

  def resume_activities
    Book.public_activity_on
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @categories = Book.pluck(:category).uniq

    if current_user
      @userReadList = current_user.books_reads.select(:isbn).map{ |elem| elem.isbn }
      @userWishList = current_user.books_wishlists.select(:isbn).map{ |elem| elem.isbn }
      @userReadingList = current_user.books_readings.select(:isbn).map{ |elem| elem.isbn }
    end

    if params[:categories]
      if params[:title] == ""
        @books = Book.where(category: params[:categories]).paginate(:page => params[:page], per_page: 10).order('id DESC')
      else
        @books = Book.where('lower(title) like ?', "%#{params[:title].downcase}%").where(category: params[:categories]).paginate(:page => params[:page], per_page: 10).order('id DESC')
      end
    else
      if !params[:title] or params[:title] == ""
        @books = Book.paginate(:page => params[:page], per_page: 10).order('id DESC')
      else
        @books = Book.where('lower(title) like ?', "%#{params[:title].downcase}%").paginate(:page => params[:page], per_page: 10).order('id DESC')
      end
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @bookAlreadyExists = Book.exists?(isbn: book_params["isbn"].to_i)
    @book = Book.new(book_params)
    @book.user = current_user

    respond_to do |format|
      if  @bookAlreadyExists
        format.html { redirect_to new_book_path, alert: 'Book with this ISBN already exists in the bookshelf.' }
      elsif @book.save
        format.html { redirect_to book_path(@book), notice: 'Book was successfully added.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(update_only_book_params)
        format.html { redirect_to @book, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    without_tracking(Book) do
      @book.destroy
    end
    respond_to do |format|
      format.html { redirect_to user_dashboard_path, notice: 'Book was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def addToCurrentlyReading
    book = Book.find(params[:bookid].to_i)
    book.user = current_user
    @currentlyreadinglist = BooksReading.new(book.attributes.except("id", "location"))
    respond_to do |format|
      if @currentlyreadinglist.save
        format.json { render json: {success: true}}
      else
        format.json { render json: {success: false}}
      end
    end
  end

  def destroyCurrentlyReading
    book = BooksReading.find(params[:id].to_i)
    book.user = current_user
    @booksread = BooksRead.new(book.attributes.except("id", "location"))

    without_tracking(BooksReading) do
      books_reading = current_user.books_readings
      books_reading.find(params[:id].to_i).destroy()
    end

    respond_to do |format|
      if @booksread.save
        format.html { redirect_to :back, notice: 'Book was successfully moved to your "Read" list.' }
        format.json { head :no_content }
      else
        format.json { render json: {success: false}}
      end
    end
  end

  def addToWishList
    book = Book.find(params[:bookid].to_i)
    book.user = current_user
    @wishlist = BooksWishlist.new(book.attributes.except("id", "location"))
    respond_to do |format|
      if @wishlist.save
        format.json { render json: {success: true}}
      else
        format.json { render json: {success: false}}
      end
    end
  end

  def destroyWishList
    books_wishlist = current_user.books_wishlists
    without_tracking(BooksWishlist) do
      books_wishlist.find(params[:id].to_i).destroy()
    end
    respond_to do |format|
      format.html { redirect_to user_dashboard_path, notice: 'Book was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def addToAlreadyRead
    book = Book.find(params[:bookid].to_i)
    book.user = current_user
    @alreadyReadList = BooksRead.new(book.attributes.except("id", "location"))
    respond_to do |format|
      if @alreadyReadList.save
        format.json { render json: {success: true}}
      else
        format.json { render json: {success: false}}
      end
    end
  end

  def destroyAlreadyRead
    books_read = current_user.books_reads
    without_tracking(BooksRead) do
      books_read.find(params[:id].to_i).destroy()
    end
    respond_to do |format|
      format.html { redirect_to user_dashboard_path, notice: 'Book was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def addRecommendation
    book = Book.find(params[:bookid].to_i)
    userids = book.recommendation.map{ |elem| elem.user_id }
    canUseAddRecommendation = !userids.include?(current_user.id)
    book.recommendation.new(user_id: current_user.id, user_recommendation: params[:recommendation])
    without_tracking(Book) do
      respond_to do |format|
        if canUseAddRecommendation and book.save
          format.json { render json: {success: true}}
        else
          format.json { render json: {success: false}}
        end
      end
    end
  end

  def deleteRecommendation
    without_tracking(Recommendation) do
      recommendation = Recommendation.find(params[:id])
      respond_to do |format|
        if recommendation.destroy
          format.html { redirect_to user_dashboard_path, notice: 'Recommendation was successfully deleted.' }
          format.json { head :no_content }
        else
          format.html { redirect_to user_dashboard_path, alert: 'Failed to delete the recommendation. Please try again.' }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:error] = "The book seems to have been deleted!"
        redirect_to :back
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn, :googleid, :category, :apiLink, :title, :publisher, :publishedDate, :author, :averageRating, :ratingsCount, :description, :imageurl)
    end

    def update_only_book_params
      params.require(:book).permit(:location)
    end

    def without_tracking(modalName)
      modalName.public_activity_off
      yield if block_given?
      modalName.public_activity_on
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<% @books.each do |book, index| %>
  <div id="book-<%= book.id %>" class="custom-well book-container" data-googleLink="<%= book.apiLink %>">
    <div class="row">
      <div class="col-lg-12">
        <div class="notifications-<%= book.id %>">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-9">
        <a href="/books/<%= book.id %>" class="book-<%= book.id %>__linktag">
          <h3 class="book__title book-<%= book.id %>__title"><%= book.title %></h3>
          <% if book.recommendation.any? %>
            <span class="label label-default recommended-label"><i class="fa fa-star" aria-hidden="true"></i> Recommended</span>
          <% end %>
          <span class="book-info-span-one book-<%= book.id %>__authors">by <%= book.author %></span>
        </a>
        <h5>Category: <span><%= book.category %></span></h5>
      </div>
      <div class="col-lg-3 col-sm-12">
        <% if current_user and !book.recommendation.map{|elem| elem.user_id}.include?(current_user.id) %>
        <button type="button" class="btn btn-small btn-recommendation book-<%= book.id %>__addRecommendation" data-bookid="<%= book.id %>" data-target="#modal">
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Add a review
        </button>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2 col-md-2 col-sm-12">
        <% if book.imageurl and book.imageurl != "" %>
          <%= image_tag book.imageurl , class: "book-#{book.id}__image book__image", width: "150" %>
        <% else %>
          <%= image_tag 'no_cover_thumb.gif' , class: "book-#{book.id}__image book__image", width: "150" %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <p class="book-<%= book.id %>__description book__description"><%= book.description ? book.description.html_safe : "" %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <h5 class="book-info-h5">Written by: <span class="book-info-span book-<%= book.id %>__authors"><%= book.author %></span></h5>
        <h5 class="book-info-h5">Average Rating (from <span class="book-info-span book-<%= book.id %>__totalRatings">
          <%= book.ratingsCount == 0 ? "N/A" : book.ratingsCount %></span> ratings):
          <span class="book-<%= book.id %>__avgRating"><%= book.averageRating == 0 ? "N/A" : book.averageRating %></span>
        <h5>
        <% if book.user %>
          <h5 class="">Added by:
            <a href="/users/<%= book.user.id %>"><span class="book-<%= book.id %>__addedby book__addedby"><%= book.user.name %></span></a>
          </h5>
        <% end %>
      </div>
    </div>
    <% if current_user %>
      <div class="book-<%= book.id %>__dropdown dropdown">
        <button class="btn dropdown-toggle add-book-to-list-btn" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Add to list
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu add-book-to-list-dropdown" data-bookid="<%= book.id %>" aria-labelledby="add-book-to-list-dropdown" data-bookid="<%= book.id %>">
          <li class="<%= 'disabled' if @userReadingList.include?(book.isbn) or @userWishList.include?(book.isbn) %> <%= 'disabled bg-success' if @userReadList.include?(book.isbn) %>"><%= link_to 'Read', add_to_read_path, class: 'add-to-read' %></li>
          <li class="<%= 'disabled' if @userReadList.include?(book.isbn) or @userWishList.include?(book.isbn) %> <%= 'disabled bg-success' if @userReadingList.include?(book.isbn) %>"><%= link_to 'Currently Reading', add_to_currently_reading_path, class: 'add-to-currently-reading' %></li>
          <li class="<%= 'disabled' if @userReadingList.include?(book.isbn) or @userReadList.include?(book.isbn) %> <%= 'disabled bg-success' if @userWishList.include?(book.isbn) %>"><%= link_to 'Wishlist', add_to_wish_list_path, class: 'add-to-wish-list' %></li>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/_bookResults.html.erb
<div class="row gbData__container">
  <div class="col-lg-12">
    <div class="gbData">
      <img class="gbData__thumbnailImage" width="200" />
      <a  bind-href="googleLink" target="_blank"><h4 bind="title"></h4></a>
      <p class="new-book-description"></p>
      <span bind="categories"></span>
      <p bind="authors"></p>
    </div>
  </div>
</div>

app/views/books/_currentlyReadingList.html.erb
<h5 class="table__heading">Your reading list:</h5>
<table class="table table-striped currentlyReadingList">
  <thead>
    <tr>
      <th class="table__subheading">ISBN</th>
      <th class="table__subheading">Title</th>
      <% if @user.id == current_user.id %>
        <th class="table__subheading">Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% obj.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= link_to book.title, books_path(:title => book.title) %></td>
        <% if @user.id == current_user.id %>
          <td>
            <%= link_to 'Mark as completed.', remove_from_currently_reading_path(book), :method => :delete,
             :data => { :confirm => "Are you sure?"},
             :class => "btn btn-xs btn-success" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_form.html.erb
<%= render 'shared/errors', obj: @book %>

<%= form_for @book, :html => { :class => "form-horizontal book", role: "form" } do |f| %>

  <div class="form-group form-group-isbn">
    <%= label_tag 'ISBN', nil, :class => 'isbn-label control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= number_field_tag 'ISBN (optional)', nil, :class => 'form-control query-isbn', placeholder: "Search by ISBN"%>
    </div>
  </div>
  <div class="form-group form-group-title">
    <%= label_tag 'Title', nil, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_field_tag 'Title', nil, :class => 'form-control query-title', placeholder: "Search by title", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Add Book', :class => 'btn submit-btn', disabled: true %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-cancel' %>
    </div>
  </div>

  <%= f.hidden_field :isbn, bind: "isbn" %>
  <%= f.hidden_field :title, bind: "title" %>
  <%= f.hidden_field :googleid, bind: "id" %>
  <%= f.hidden_field :category, bind: "categories" %>
  <%= f.hidden_field :apiLink, bind: "selfLink" %>

  <%= f.hidden_field :publisher, bind: "publisher" %>
  <%= f.hidden_field :publishedDate, bind: "publishedDate" %>
  <%= f.hidden_field :author, bind: "authors" %>
  <%= f.hidden_field :averageRating, bind: "avgRating" %>
  <%= f.hidden_field :ratingsCount, bind: "totalRatings" %>
  <%= f.hidden_field :description, bind: "description" %>
  <%= f.hidden_field :imageurl, bind: "imageurl" %>

  <%= render :partial => 'bookResults' %>
<% end %>

app/views/books/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th class="table__subheading">ISBN</th>
      <th class="table__subheading">Title</th>
    </tr>
  </thead>
  <tbody>
    <% obj.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= link_to book.title, books_path(:title => book.title) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_myList.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th class="table__subheading">ISBN</th>
      <th class="table__subheading">Title</th>
      <% if @user.id == current_user.id %>
        <th class="table__subheading">Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% obj.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= link_to book.title, books_path(:title => book.title) %></td>
        <% if @user.id == current_user.id %>
          <td>
            <%= link_to 'Delete', book_path(book), :method => :delete,
             :data => { :confirm => "Are you sure?"},
             :class => "btn btn-xs btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_readList.html.erb
<h5 class="table__heading">Books you have finished reading:</h5>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="table__subheading">ISBN</th>
      <th class="table__subheading">Title</th>
      <% if @user.id == current_user.id %>
        <th class="table__subheading">Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% obj.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= link_to book.title, books_path(:title => book.title) %></td>
        <% if @user.id == current_user.id %>
          <td>
            <%= link_to 'Remove', remove_from_already_read_path(book), :method => :delete,
             :data => { :confirm => "Are you sure?"},
             :class => "btn btn-xs btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_recommendationmodal.html.erb
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-bookid="">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <form class="recommendation__form">
      <div class="modal-body">
        <input type="hidden" class="modal__bookidInput" >
        <div class="form-group">
          <label for="recommendation">Review:</label>
          <textarea type="text" class="form-control" id="recommendation" placeholder="What did you like about this book? How did it benefit you?" required="true"></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-submit-review">Add Review</button>
      </div>
      </form>
    </div>
  </div>
</div>

app/views/books/_wishlist.html.erb
<h5 class="table__heading">Your Wishlist:</h5>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="table__subheading">ISBN</th>
      <th class="table__subheading">Title</th>
      <% if @user.id == current_user.id %>
        <th class="table__subheading">Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% obj.each do |book| %>
      <tr>
        <td><%= book.isbn %></td>
        <td><%= link_to book.title, books_path(:title => book.title) %></td>
        <% if @user.id == current_user.id %>
          <td>
            <%= link_to 'Remove', remove_from_wish_list_path(book), :method => :delete,
             :data => { :confirm => "Are you sure?"},
             :class => "btn btn-xs btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'shared/errors', obj: @book %>

<%= form_for @book, :html => { :class => "form-horizontal book", role: "form" } do |f| %>
<div class="row custom-well">
  <div class="form-group form-group-location">
    <%= label_tag 'Where can people find this book?', nil, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, class: 'form-control', required: true, placeholder: "Example. 9th Floor - User Experience Pod or 8th Floor Bookshelf" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary'%>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>
<% end %>

app/views/books/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "books", :media => "all" %>
<% end %>

<%- model_class = Book -%>
<div class="row">
  <div class="col-sm-12 col-md-5 col-md-push-3">
    <%= form_tag books_path,  method: :get, id: 'filter-books-form', class: 'custom-well' do |form| %>
    <h4>Filter:</h4>
      <div class="form-group">
        <%= label_tag :title, nil, :class => 'control-label' %>
        <%= text_field_tag :title, params[:title], :class => 'form-control query-title', placeholder: "Search by title" %>
      </div>
      <h5 class="categories-heading">Categories:</h5>
      <div class="radio">
        <% @categories.each do |category| %>
            <label class="category-radiobtn">
              <%= check_box_tag  "categories[]", "#{category}",  (if params[:categories] then params[:categories].include? category end) %>
               <%= category %>
            </label>
          <% end %>
      </div>
      <div>
        <%= submit_tag("Apply Filters", :class => 'btn btn-apply-filter') %>
        <%= link_to 'Remove Filters', books_path, :class => 'btn btn-remove-filter' %>
      </div>
    <% end %>
  </div>
</div>

<div class="">
  <div align="center">
      <%= will_paginate @books, :previous_label => "&#8592", :next_label => "&#8594" %>
  </div>
  <%= render 'book', :obj => @books %>
  <div align="center">
      <%= will_paginate %>
  </div>
</div>

<%= render 'recommendationmodal' %>

<% content_for :scripts do %>
  <%= javascript_include_tag 'books' %>
<% end %>

app/views/books/new.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "newBook", :media => "all" %>
<% end %>

<%- model_class = Book -%>

<div class="row">
  <div class="col-lg-12 custom-well">
    <h5 class="text-box-heading">Search by ISBN or Title</h5>
    <h5 class="text-box-subheading">Cannot find the book you want to add? Don't worry. Fill out <a href="https://goo.gl/forms/ccPKH0lp98zCmG103" target="_blank">this form</a> and I will take care of the rest :D</h5>
    <%= render :partial => 'form' %>
  </div>
</div>

<% content_for :scripts do %>
  <%= javascript_include_tag 'addNewBook' %>
<% end %>

app/views/books/search.html.erb
<h1>This is the search page for books.</h1>

app/views/books/show.html.erb
<%- model_class = Book -%>

<% content_for :head do %>
  <%= stylesheet_link_tag "books", :media => "all" %>
<% end %>

<div id="book" class="custom-well show-book-container">
  <div class="row">
    <div class="col-lg-12">
      <div class="notifications-<%= @book.id %>">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-9">
      <a href=<%= "http://books.google.ca/books?id=#{@book.googleid}" %> target="_blank" class="book__linktag">
        <h3 class="book__title"><%= @book.title %></h3>
        <% if @book.recommendation.any? %>
          <span class="label label-default recommended-label"><i class="fa fa-star" aria-hidden="true"></i> Recommended</span>
        <% end %>
      </a>
    </div>
    <div class="col-lg-3">
      <% if !@book.recommendation.map{|elem| elem.user_id}.include?(current_user.id) %>
      <button type="button" class="btn btn-small btn-recommendation book-<%= @book.id %>__addRecommendation" data-bookid="<%= @book.id %>" data-target="#modal">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Add a Review
      </button>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-2">
      <% if @book.imageurl and @book.imageurl != "" %>
        <%= image_tag @book.imageurl , class: "book__image", width: "150" %>
      <% else %>
        <%= image_tag 'no_cover_thumb.gif' , class: "book__image", width: "150" %>
      <% end %>
    </div>
    <div class="col-lg-10 book-info">
      <h5>Publisher: <span class="book__publisher"><%= @book.publisher %></span></h5>
      <h5>Published Date: <span class="book__publishedDate"><%= @book.publishedDate %></span></h5>
      <h5>Category: <span><%= @book.category %></span></h5>
      <h5>Written by: <span class="book__authors"><%= @book.author %></span></h5>
      <h5>ISBN: <span><%= @book.isbn %></span></h5>
      <h5>Average Rating (from <span class="book__totalRatings"><%= @book.ratingsCount %></span> ratings): <span class="book__avgRating"><%= @book.averageRating %></span><h5>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <p class="book__description"><%= @book.description ? @book.description.html_safe : "" %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h5 class="">Added by: <a href="/users/<%= @book.user.id %>"><span class="book__addedby"><%= @book.user.name %></span></a></h5>
    </div>
  </div>

  <% if @book.recommendation.any? %>
    <div class="row">
      <div class="col-lg-12">
        <h4>Reviews:</h4>
        <ul class="list-group">
          <% @book.recommendation.order('id DESC').each do |post| %>
          <li class="list-group-item">
            <p class="recommendation__text">
              "<%= post.user_recommendation %>"
            </p>
            <% @owner = User.find(post.user_id) %>
            <h5 class="recommendation__user">- <%= link_to @owner.name, user_path(post.user_id) %> - <%= @owner.position %> </h5>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-12">
      <% if current_user == @book.user %>
        <%= link_to t('.back', :default => t("helpers.links.back")),
                      books_path, :class => 'btn btn-default'  %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      book_path(@book),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'recommendationmodal' %>

<% content_for :scripts do %>
  <%= javascript_include_tag 'showBook' %>
<% end %>