config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users,  :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth" }
  resources :users, only: [:show]
  root 'stories#index'

  get '/about' => 'welcome#index'

  post '/addrecommendation' => 'books#addRecommendation'
  match '/deleterecommendation' => 'books#deleteRecommendation', :via => :delete, :as => :delete_recommendation

  resources :stories, except: [:index] do
    member do
      post :like
    end
  end

  as :users do
    match '/users' => 'users#index', :via => :get, :as => :show_all_users
    match '/dashboard' => 'users#dashboard', :via => :get, :as => :user_dashboard
    match '/deleteaccount' => 'users#destroy', :via => :get, :as => :delete_my_account
    match '/inviteuser' => 'users#create_invitation', :via => :post, :as => :invite_user
  end

  as :books do
    match '/currentlyreadinglist' => 'books#addToCurrentlyReading', :via => :post, :as => :add_to_currently_reading
    match '/wishlist' => 'books#addToWishList', :via => :post, :as => :add_to_wish_list
    match '/read' => 'books#addToAlreadyRead', :via => :post, :as => :add_to_read
    match '/destroycurrentlyreading/:id' => 'books#destroyCurrentlyReading', :via => :delete, :as => :remove_from_currently_reading
    match '/destroywishlist/:id' => 'books#destroyWishList', :via => :delete, :as => :remove_from_wish_list
    match '/destroyalreadyread/:id' => 'books#destroyAlreadyRead', :via => :delete, :as => :remove_from_already_read
  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  before_destroy :pause_tracking
  after_destroy :resume_activities

  has_many :likes, dependent: :destroy

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user },
          title: Proc.new { |controller, model| model.title }

  def pause_tracking
    Story.public_activity_off
    return true
  end

  def resume_activities
    Story.public_activity_on
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :find_story, only: [:destroy, :show, :edit, :update, :like]
  before_action :load_activities, only: [:index, :show, :new, :edit]

  def index
    @stories = Story.limit(40).order('created_at DESC')
    @story = Story.new
  end

  def new
  end

  def create
    @story = Story.new(story_params)
    @story.user = current_user
    if @story.save
      flash[:success] = 'Your story was added!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @story.update_attributes(story_params)
      flash[:success] = 'The story was edited!'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    without_tracking do
      if @story.destroy
        flash[:success] = 'The story was deleted!'
      else
        flash[:error] = 'Cannot delete this story...'
      end
    end
    redirect_to root_path
  end

  def show
  end

  def like
    without_tracking do
      @likes = Like.new(user_id: current_user.id, story_id: @story.id, title: @story.title)
    end
    if @likes.save
      flash[:success] = 'Thanks for the like!'
    else
      flash[:error] = 'Please try again.'
    end
    redirect_to :back
  end

  private

  def story_params
    params.require(:story).permit(:title, :body)
  end

  def like_params
    params.require(:likes).permit(:user_id, :story_id)
  end

  def find_story
    @story = Story.find(params[:id])
  end

  def load_activities
    @activities = PublicActivity::Activity.limit(40).order('created_at DESC')
  end

  def without_tracking
    Story.public_activity_off
    yield if block_given?
    Story.public_activity_on
  end
end

app/views/stories/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
  <%= render 'shared/errors', obj: @story %>
  <div class="form-group">
    <%= f.label 'Name of the book:' %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Example: Man's Search for Meaning by Viktor Emil Frankl", required: true %>
  </div>

  <div class="form-group">
    <%= f.label 'Quote / Learning:' %>
    <%= f.text_area :body, class: 'form-control', placeholder: "Happiness cannot be pursued; it must ensue.", required: true, rows: 5 %>
  </div>

  <%= f.submit 'Share', class: 'btn btn-primary' %>
<% end %>

app/views/stories/_list.html.erb
<% @stories.each do |story| %>
  <div class="story">
    <h4 class="story__heading"><%= link_to story.title, story_path(story) %></h4>

    <p class="story__content">"<%= truncate(story.body, length: 350) %>"</p>

    <p class="story__addedBy">
      Added by: <%= story.user.name %>
    </p>
    <% if current_user %>
      <p class="story__buttons">
        <span class="badge story__buttons__likecount"><%= pluralize(story.likes.count, 'like') %></span>
        <% if story.likes[0] and story.likes.to_a.collect { |elem| elem.user_id }.include? current_user.id %>
        <span class="story__buttons__likebtn">Liked!</span>
        <% else %>
          <%= link_to content_tag(:span, '', class: 'fa fa-thumbs-o-up') + ' Like it',
                       like_story_path(story), class: 'story__buttons__likebtn',
                       method: :post%>
        <% end %>
      </p>
    <% end %>

    <% if story.user == current_user %>
      <div class="btn-group">
        <%= link_to 'Edit', edit_story_path(story), class: 'label label-primary' %>
        <%= link_to 'Delete', story_path(story), data: {confirm: 'Are you sure?'}, method: :delete, class: 'label label-danger' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/stories/_loggedInIndex.html.erb
<div class="row">
  <div class="col-lg-8">
    <div class="col-lg-12">
      <div class="custom-well statusbox">
        <h2 class="statusbox__pageheading">Hello <span class="capitalize-text"><%= current_user.name.split[0] %></span>! Welcome to <span class="capitalize-text green-text">Shopify's Book Bar</span></h2>
        <h4 class="statusbox__subheading">Share a quote or anything new you learned from a book!</h4>
        <%= render 'form' %>
      </div>
    </div>
    <div class="col-lg-12">
      <% if @activities.any? %>
        <%= render 'shared/activities' %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="col-lg-12">
      <% if @stories.any? %>
        <div class="custom-well stories-container">
            <%= render 'list' %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-12">
      <%= render 'shared/inviteForm' %>
    </div>
  </div>
</div>

app/views/stories/_loggedOutIndex.html.erb
<style>
  body {
    background-color: #30373b;
  }
</style>
<div class="text-center custom-jumbotron">
  <h4 class="jumbotron__headingOne">Welcome to</h4>
  <h5 class="jumbotron__headingTwo">Shopify</h5>
  <h5 class="jumbotron__headingThree">Book Bar</h5>
  <ul class="jumbotron__list">
    <li>
      Share recommendations.
    </li>
    <li>
      See what other Shopifolks are reading.
    </li>
    <li>
      Decide on what to read next from over <%= Book.count %> titles.
    </li>
  </ul>
  <%= image_tag("homepage-book-illustration.png", class: 'jumbotron__image') %>
  <div class="jumbotron__ctas">
    <%= link_to "Browse books", books_path, class: "btn btn-cta btn-cta-browse" %>
    <%= link_to "Learn more", about_path, class: "btn btn-cta btn-cta-learn" %>
  </div>
</div>

app/views/stories/edit.html.erb
<% content_for :head do %>
  <title>Edit Story</title>
<% end %>

<div class="custom-well">
  <%= render 'form' %>
</div>

<% content_for :scripts do %>
<% end %>

app/views/stories/index.html.erb
<% content_for :head do %>
  <title>Shopify Book Bar</title>
  <%= stylesheet_link_tag    'homepage', media: 'all' %>
<% end %>

<% if current_user %>
  <%= render 'loggedInIndex' %>
<% else %>
  <%= render 'loggedOutIndex' %>
<% end %>

<% content_for :scripts do %>
  <%= javascript_include_tag 'homepage' %>
<% end %>

app/views/stories/new.html.erb
<% content_for :head do %>
  <title>New Cool Story</title>
<% end %>


<%= render 'form' %>

<% content_for :scripts do %>
<% end %>

app/views/stories/show.html.erb
<% content_for :head do %>
  <title><%= @story.title %></title>
  <%= stylesheet_link_tag 'storypage', media: 'all' %>
<% end %>

<div class="custom-well">
  <h1><a href="https://www.google.com/search?tbm=bks&q=<%= @story.title %>" target="_blank"><%= @story.title %></a></h1>
  <p class="story__body">
    <%= @story.body %>
  </p>
  <p class="story__likes">
    <span class="label label-default story__likes_count"><%= pluralize(@story.likes.count, 'like') %></span>
    <%= link_to content_tag(:span, '', class: 'fa fa-thumbs-o-up') + ' Like it',
                 like_story_path(@story), class: 'story__likes_btn', method: :post, disabled: (if @story.likes[0] then @story.likes[0].user_id == current_user.id end) %>
  </p>

  <% if @story.user == current_user %>
    <div class="btn-group story__actions">
      <%= link_to 'Edit', edit_story_path(@story), class: 'label label-primary' %>
      <%= link_to 'Delete', story_path(@story), data: {confirm: 'Are you sure?'}, method: :delete, class: 'label label-danger' %>
    </div>
  <% end %>
</div>