config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users,  :controllers => { registrations: 'registrations', :omniauth_callbacks => "omniauth" }
  resources :users, only: [:show]
  root 'stories#index'

  get '/about' => 'welcome#index'

  post '/addrecommendation' => 'books#addRecommendation'
  match '/deleterecommendation' => 'books#deleteRecommendation', :via => :delete, :as => :delete_recommendation

  resources :stories, except: [:index] do
    member do
      post :like
    end
  end

  as :users do
    match '/users' => 'users#index', :via => :get, :as => :show_all_users
    match '/dashboard' => 'users#dashboard', :via => :get, :as => :user_dashboard
    match '/deleteaccount' => 'users#destroy', :via => :get, :as => :delete_my_account
    match '/inviteuser' => 'users#create_invitation', :via => :post, :as => :invite_user
  end

  as :books do
    match '/currentlyreadinglist' => 'books#addToCurrentlyReading', :via => :post, :as => :add_to_currently_reading
    match '/wishlist' => 'books#addToWishList', :via => :post, :as => :add_to_wish_list
    match '/read' => 'books#addToAlreadyRead', :via => :post, :as => :add_to_read
    match '/destroycurrentlyreading/:id' => 'books#destroyCurrentlyReading', :via => :delete, :as => :remove_from_currently_reading
    match '/destroywishlist/:id' => 'books#destroyWishList', :via => :delete, :as => :remove_from_wish_list
    match '/destroyalreadyread/:id' => 'books#destroyAlreadyRead', :via => :delete, :as => :remove_from_already_read
  end

end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-slate">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('shopify-bookbar_logo.png'), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Add Books", new_book_path %></li>
          <li><%= link_to "Browse Books", books_path %></li>
          <li><%= link_to "Browse Users", show_all_users_path %></li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Browse Books", books_path %></li>
        <% end %>
        <% if current_user %>
        <li>
          <%= link_to image_tag("https://www.gravatar.com/avatar/#{current_user.gravitarhash}?d=retro", class: 'profilelink__image--thumbnail'), current_user, class: 'profilelink--thumbnail' %>
        </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle usermenu-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", user_dashboard_path, method: :get %></li>
              <li><%= link_to "About", about_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>